### ISSUE TITLE
OAuth Title in Readme

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/carbonops-v2#1]
Add OAuth logo appropriately under Tech Stacks section of Readme

**Comment by Tushar98644** [comment]
assign me @SrijanShovit

**Comment by Ghat0tkach** [comment]
may i work on this issue under GSSOC 23

**Comment by AVSanjay-12** [comment]
Please assign this to me under GSSOC 2023

**Comment by naitik-lodha** [comment]
Please assign this issue to me under GSSOC'23

**Comment by SrijanShovit** [comment]
I am very sorry for the discomfort to everyone due to my absence as I was super busy.
For preserving the spirit of open source, I am assigning the issue to @Tushar98644 on a first come first serve.

**Comment by SrijanShovit** [comment]
If the task isn't completed by 23 midnight, then I shall pass the issue to the next person.
