### ISSUE TITLE
Bug: Sign Up button is not working

### ISSUE THREAD

**Issue by suzy-g38** [SrijanShovit/carbonops-v2#100]
Clicking on the signup button nothing is happening.

I would like to work on it under gssoc'23

**Comment by SrijanShovit** [comment]
Hello suzy-g38, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Closing as same as #78 . @suzy-g38  If you want to work on #78,comment on it to get assigned
