### ISSUE TITLE
Individual Dashboard UI

### ISSUE THREAD

**Issue by shreya024** [SrijanShovit/carbonops-v2#104]
## Description:
- Make UI for Individual Dashboard after login/SignUp by an Individual 
- Set the fields for Individual Profile Completion as the following in a sideview Drawer
  - Profile Image
  - D.O.B
  - City
  - Occupation Type
  - Social Media Links
  - Address
- Use React Mui/Next UI with Tailwind CSS
- Route Calculate button to /calculate
- Route Feeds button to /feeds
- Route Events button to /events

## Design
![individual_Dashboard-Copy](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/6b932f1c-903d-4e3b-9e5a-11eb340f409e)

Drawer View for Profile Edit/Completion: 
![Edit form](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/7c1cc5bc-4d93-43fc-9dab-9b8acc3c1d20)

**Comment by SrijanShovit** [comment]
Hello shreya024, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by Ida-Naliaka** [comment]
Hi @shreya024 can I work this?
