### ISSUE TITLE
Navbar Height issue [GSSOC'23]

### ISSUE THREAD

**Issue by Ujwal19k** [SrijanShovit/carbonops-v2#105]
I noticed that the height of the navbar is too larger. Please assign me this issue. I am GGSOC'23 Contributor. Mention if additional text to be added in it. if any. 
 [GSSOC'23]
<img width="960" alt="image" src="https://github.com/SrijanShovit/carbonops-v2/assets/106575224/a407b635-4999-44ea-aac5-883d514811ea">

**Comment by SrijanShovit** [comment]
Hello Ujwal19k, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Same as #47 .Comment on it to get assigned @Ujwal19k
