### ISSUE TITLE
Vercel Integration in Github Actions

### ISSUE THREAD

**Issue by shreya024** [SrijanShovit/carbonops-v2#108]
## Description:
- Integrate Vercel in Github Actions

## Link
Refer [here](https://vercel.com/guides/how-can-i-use-github-actions-with-vercel)

**Comment by SrijanShovit** [comment]
Hello shreya024, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by guha-rahul** [comment]
hey @shreya024 i have read the link u have provided . Can u assign this issue to me?
