### ISSUE TITLE
Adding Contributors List in the Readme 

### ISSUE THREAD

**Issue by abhi03ruchi** [SrijanShovit/carbonops-v2#112]
I would like to add the Contributors List to the Readme.
A Contributors List promotes a positive and inclusive environment, fostering further participation and enhancing the project's success.

Plz assign me this task under gssoc'23.

**Comment by SrijanShovit** [comment]
Hello abhi03ruchi, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Not required
