### ISSUE TITLE
Icons issue in the website

### ISSUE THREAD

**Issue by HimanshuNarware** [SrijanShovit/carbonops-v2#114]
The website icons are not visible.

##Screenshot
![7](https://github.com/SrijanShovit/carbonops-v2/assets/83147410/6febce80-ce41-40a7-9ede-a91b31ba31c6)
![5](https://github.com/SrijanShovit/carbonops-v2/assets/83147410/21375400-f35c-4d63-abcb-2edb8f17fb15)

**Comment by SrijanShovit** [comment]
Hello HimanshuNarware, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Closing as same issue as #94
