### ISSUE TITLE
Style :Footer Icon Hover

### ISSUE THREAD

**Issue by parasss19** [SrijanShovit/carbonops-v2#119]
### Current
- No hovering effect on social icons on footer

<img width="960" alt="2023-06-18 (2)" src="https://github.com/SrijanShovit/carbonops-v2/assets/101205226/483f2bea-ea3b-489a-a143-9a9e87cd5598">

**Comment by SrijanShovit** [comment]
Hello parasss19, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Closing as not required
