### ISSUE TITLE
Fixing mobile navbar

### ISSUE THREAD

**Issue by Soulpurr** [SrijanShovit/carbonops-v2#120]
The navbar in mobile is overflowing.
![Screenshot_2023-06-20-12-25-17-01_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/SrijanShovit/carbonops-v2/assets/92094765/6533712a-0888-4d23-84a4-2b956df7b780)
Pls assign this to me under gssoc23

**Comment by SrijanShovit** [comment]
Hello Soulpurr, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Same as #47
