### ISSUE TITLE
Make NavBar more User-Friendly!

### ISSUE THREAD

**Issue by sabhisharma-ise** [SrijanShovit/carbonops-v2#121]
The NavBar of the website looks currently like this:-

![image](https://github.com/SrijanShovit/carbonops-v2/assets/100849696/e94269c3-5e0b-453a-ac88-4991f3b47c73)

It does not looks very professional as the NavBar is taking up a whole lot of space in the website when a user scrolls down the webpage.

Kindly assign me this issue, so that I can fix it !

**Comment by SrijanShovit** [comment]
Hello sabhisharma-ise, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Same as #47
