### ISSUE TITLE
Add Relevant Content to About Section!

### ISSUE THREAD

**Issue by sabhisharma-ise** [SrijanShovit/carbonops-v2#122]
The About Section of the Website currently has no content related to the website.

I would like to work on this issue and add relevant content to the About Page of this website!

GSSOC'23 Contributor

**Comment by shreya024** [comment]
@sabhisharma-ise What relevant content do you want to add?

**Comment by sabhisharma-ise** [comment]
@shreya024 I think i'll add the Mission and Who are we? section....like getting the relevant information from the readme.md or either you can also provide the content to me

**Comment by shreya024** [comment]
Cuurently we are focused more on the functionality and apis and UIs ,we havn't thought about the content part yet

**Comment by sabhisharma-ise** [comment]
Alright Thanks
