### ISSUE TITLE
[FEATURE]: add codeql workflow 

### ISSUE THREAD

**Issue by harmeetsingh11** [SrijanShovit/carbonops-v2#124]
### Is your feature request related to a problem ? Please describe. ✍️

The repository contains code in `javascript`, it does not have workflow for code scanning.

### Describe briefly how you would implement this enhancement.

I will add the `codeql.yml` workflow to automate security checks. CodeQL is the code analysis engine developed by GitHub to identify vulnerabilities in code. It will analyze your code and display the results as code scanning alerts. It will be enabled on every push, commit and pull request using GitHub actions.

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I am a GSSoC23 Contributor.
- [x] I would like to work on this issue.

**Comment by shreya024** [comment]
We already have GitGuardian and dependabot for this

**Comment by harmeetsingh11** [comment]
@shreya024 GitGuardian scans source code to detect API keys, Passwords and other sensitive data. CodeQL scans for vulnerabilities in source code.

**Comment by shreya024** [comment]
> @shreya024 GitGuardian scans source code to detect API keys, Passwords and other sensitive data. CodeQL scans for vulnerabilities in source code.

We have Dependabot for vulnerability checking

**Comment by harmeetsingh11** [comment]
Dependabot only alerts when it detects that your repository uses a vulnerable dependency. It doesn't scan your whole repository for vulnerability.
