### ISSUE TITLE
I WOULD LIKE TO WORK ON LOGIN PAGE

### ISSUE THREAD

**Issue by Soulpurr** [SrijanShovit/carbonops-v2#126]
I would like to work on overall responsiveness of login page.
![Screenshot_2023-06-20-21-44-33-69_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/SrijanShovit/carbonops-v2/assets/92094765/f1c6f712-17c5-40c2-9036-303881ce3a2c)
Pls assign this to me under gssoc23

**Comment by shreya024** [comment]
Same as #111
