### ISSUE TITLE
Add the prettier linter workflow

### ISSUE THREAD

**Issue by metabiswadeep** [SrijanShovit/carbonops-v2#127]
**Description**
As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using the prettier linter in GitHub actions.

**Solution**
Add the prettier linter to ensure proper and uniform linting of the codebase. 

I would like to work on this as a part of GSSoC 23.

**Comment by SrijanShovit** [comment]
Hello metabiswadeep, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Closing as Not required
