### ISSUE TITLE
Feeds Page UI

### ISSUE THREAD

**Issue by shreya024** [SrijanShovit/carbonops-v2#128]
## Description:
- Make UI for Feeds Page 
- Set the route to /feeds
- Use React Mui/Next UI with Tailwind CSS

## Design
![Feeds page](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/7bcb1238-9d03-48ae-bc68-7563d27e3a17)

**Comment by SrijanShovit** [comment]
Hello shreya024, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by MahendraDani** [comment]
@shreya024 I would like to work on this issue!

**Comment by karantec** [comment]
I am from GSSoC'23.
I would like to be assigned this task.

**Comment by MahendraDani** [comment]
@karantec I could not work on this issue due to some conflicts in my previous PRs. 
Since it has been over 5 days, I am unassigning myself!
The maintainers might assign this issue to you.
Good luck!

**Comment by MahendraDani** [comment]
@shreya024 
Would you please re-assign this issue to me?

**Comment by shreya024** [comment]
@MahendraDani Any updates?

**Comment by MahendraDani** [comment]
@shreya024 
I will make the PR by tonight, it's almost done!
