### ISSUE TITLE
Adding a scrollup option in page.js

### ISSUE THREAD

**Issue by Deepanshu0703** [SrijanShovit/carbonops-v2#13]

**Comment by Deepanshu0703** [comment]
Plz do assign it to me

**Comment by khushi1711** [comment]
i would like to work on this. assign this to me

**Comment by shreya024** [comment]
> Plz do assign it to me 

@Deepanshu0703 Assigned

**Comment by Deepanshu0703** [comment]
Ok I will make  PR in evening thanks to assign
