### ISSUE TITLE
Want to add hover effect on the registration page icons

### ISSUE THREAD

**Issue by HimanshuNarware** [SrijanShovit/carbonops-v2#130]
##Description
I want to add a hover effect on the registration page icons, this will improve the UI of the website. I want  to work on this issue.

##Screenshot
![22](https://github.com/SrijanShovit/carbonops-v2/assets/83147410/163a1b3a-4cfc-4f04-a114-f64e9b142a73)

**Comment by SrijanShovit** [comment]
Hello HimanshuNarware, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Not required
