### ISSUE TITLE
The Contributor image is overriding the navbar

### ISSUE THREAD

**Issue by HimanshuNarware** [SrijanShovit/carbonops-v2#131]
##Description
In the Meet Our Team section the contributor image overrides the navbar when we hover over the image of the contributor. I want to work on this issue.

##Screenshot
![24](https://github.com/SrijanShovit/carbonops-v2/assets/83147410/7be5d188-3392-4925-9230-9248d531e1de)
![23](https://github.com/SrijanShovit/carbonops-v2/assets/83147410/bbd25d21-be28-448d-bc41-4fc0c586cbb5)

**Comment by SrijanShovit** [comment]
Hello HimanshuNarware, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Not an issue in local. #47 would solve it
