### ISSUE TITLE
Enhance UI of the navbar

### ISSUE THREAD

**Issue by Pragati-3003** [SrijanShovit/carbonops-v2#132]
Hey ,I would like to change of the Navbar .
Also, the height of the navbar is not favorable.
So,please assign this issue to me under gssoc23
![Screenshot 2023-06-21 160704](https://github.com/SrijanShovit/carbonops-v2/assets/132778037/ef502f50-da65-4f65-981b-b55b5c0c4750)
.

**Comment by SrijanShovit** [comment]
Hello Pragati-3003, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Closing as same as #47
