### ISSUE TITLE
Add CodeQL Workflow

### ISSUE THREAD

**Issue by abhinav-m22** [SrijanShovit/carbonops-v2#133]
Although the repository has javascript code, it lacks workflow for code inspection.
The codeql.yml workflow file will be added by me to automate security checks.
CodeQL is a code analysis tool, to find vulnerabilities in programs. The code will be examined, and the results will be presented as code scanning alerts. Every push, commit, and pull request that uses GitHub actions will have it enabled.

I want to work on this issue under GSSoC'23

**Comment by SrijanShovit** [comment]
Hello abhinav-m22, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Already have GitGuardian and dependabot for that
