### ISSUE TITLE
Products Page UI

### ISSUE THREAD

**Issue by shreya024** [SrijanShovit/carbonops-v2#138]
## Description:
- Make UI for Products Page 
- Set the route to /products
- Use React Mui/Next UI with Tailwind CSS

## Design
![products-page](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/322f0dca-57d6-4cbf-8721-87b4ee732bac)

**Comment by SrijanShovit** [comment]
Hello shreya024, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by MahendraDani** [comment]
@shreya024 I would like to work on this issue!
