### ISSUE TITLE
Add a contact us page.

### ISSUE THREAD

**Issue by Soulpurr** [SrijanShovit/carbonops-v2#139]
I would like to add a contact us page.
Pls assign this to me under gssoc23

**Comment by SrijanShovit** [comment]
Hello Soulpurr, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Same as #33 .If you would like to work on it,comment there

**Comment by Soulpurr** [comment]
> Same as #33 .If you would like to work on it,comment there

Yea definitely I wood like to work on that.

**Comment by shreya024** [comment]
> > Same as #33 .If you would like to work on it,comment there
> 
> Yea definitely I wood like to work on that.

Comment in #33

**Comment by Soulpurr** [comment]
> > > Same as #33 .If you would like to work on it,comment there
> > 
> > 
> > Yea definitely I wood like to work on that.
> 
> Comment in #33

Check
