### ISSUE TITLE
Add light theme

### ISSUE THREAD

**Issue by linga66** [SrijanShovit/carbonops-v2#141]
This website does not contain the light theme
I want to add the toggle button that switches from both the theme

**Comment by SrijanShovit** [comment]
Hello linga66, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Same as #62 .If you would like to work on it,comment there

**Comment by linga66** [comment]
Yes I want to work on this!
