### ISSUE TITLE
[Feature]: Add a completely responsive footer as per website theme  

### ISSUE THREAD

**Issue by MAYANKpandey14** [SrijanShovit/carbonops-v2#142]
To add a responsive and attractive footer to provide a better user experience.

Picture of a completely responsive footer i created for another project 
![crop-footer-sample](https://github.com/SrijanShovit/carbonops-v2/assets/94740455/8864fb69-5192-4816-bba9-a1602ea11fcb)

Kindly Assign this to me under gssoc "23

**Comment by SrijanShovit** [comment]
Hello MAYANKpandey14, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by MAYANKpandey14** [comment]
Thanks for the warm welcome

**Comment by shreya024** [comment]
@MAYANKpandey14 This issue is same as #47 .If you would like to work on it,comment there
