### ISSUE TITLE
[Bug] Minimalist Footer

### ISSUE THREAD

**Issue by harshit-tiwaari** [SrijanShovit/carbonops-v2#144]
The footer of the website is very broad. Want to make it less broad and will it make minimalistic.
![image](https://github.com/SrijanShovit/carbonops-v2/assets/104323483/404f16a7-ddbb-4e95-b21e-ba0e12c0befb)

**Comment by SrijanShovit** [comment]
Hello harshit-tiwaari, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Same as #47
