### ISSUE TITLE
Bug: Hero imgage overlap navbar

### ISSUE THREAD

**Issue by parasss19** [SrijanShovit/carbonops-v2#145]
## Current 
- Hero image overlap the navbar

<img width="954" alt="Screenshot 2023-06-23 235359" src="https://github.com/SrijanShovit/carbonops-v2/assets/101205226/9dc05ab1-ed93-4a91-a581-016fdfb128c5">

## Change
- I will make it proper by using  correct css property

**Comment by SrijanShovit** [comment]
Hello parasss19, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>
