### ISSUE TITLE
Feature: Modify Issue Template

### ISSUE THREAD

**Issue by parasss19** [SrijanShovit/carbonops-v2#146]
## Current 
- The issue template doesn't have  separate yml files for bug , feature and documentation related issues
- It is very difficult for sometime for project admins to put the correct labels on the issues
<img width="960" alt="Screenshot 2023-06-23 235536" src="https://github.com/SrijanShovit/carbonops-v2/assets/101205226/5e392742-d009-45ba-a506-1ccfca647f5b">

## Change 

- I will add separate yml files for  for bug , feature and documentation related issues

## 1 Sample
<img width="880" alt="Screenshot 2023-06-20 232906" src="https://github.com/SrijanShovit/carbonops-v2/assets/101205226/572204f3-381e-4ff2-b418-e65575d502c2">

## 2 Sample
<img width="721" alt="temp img" src="https://github.com/SrijanShovit/carbonops-v2/assets/101205226/31267509-b132-432b-80da-c272a5bd3c3a">

**Comment by SrijanShovit** [comment]
Hello parasss19, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Not required
