### ISSUE TITLE
[FEATURE] To Use src Directory For Improved Code Organization

### ISSUE THREAD

**Issue by s2sharpit** [SrijanShovit/carbonops-v2#148]
I hope this message finds you well. I am writing to raise an issue and propose an enhancement. After careful consideration, I believe that incorporating the feature of Next.js 13, which allows for the addition of an "src" folder, could significantly improve the code organization within our project.

The primary objective of this enhancement is to separate the application code from the project configuration files, which typically reside in the root directory of the project. By adopting this practice, we can achieve better code clarity, maintainability, and ease of collaboration.

**Comment by SrijanShovit** [comment]
Hello s2sharpit, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
> I hope this message finds you well. I am writing to raise an issue and propose an enhancement. After careful consideration, I believe that incorporating the feature of Next.js 13, which allows for the addition of an "src" folder, could significantly improve the code organization within our project.
> 
> The primary objective of this enhancement is to separate the application code from the project configuration files, which typically reside in the root directory of the project. By adopting this practice, we can achieve better code clarity, maintainability, and ease of collaboration.

@s2sharpit  We are working in Next.js 13.4. Let me know if you feel that src will improve code organization in 13.4 as well and I will assign this issue to you.

**Comment by s2sharpit** [comment]
> @s2sharpit We are working in Next.js 13.4. Let me know if you feel that src will improve code organization in 13.4 as well and I will assign this issue to you.

Thank you for your response, @shreya024 . I'm glad to hear that Next.js 13.4 is being worked on, and I believe that incorporating the "src" folder would be beneficial for code organization in this version as well.

The separation of application code from project configuration files through the "src" folder can greatly enhance code clarity, maintainability, and collaboration. It allows for a more structured and organized codebase, making it easier to locate and work with specific code modules.

I'm confident that implementing this feature will contribute to improved code organization across all versions, including Next.js 13.4. Therefore, I would be happy to take ownership of this issue and contribute to its implementation.

Please assign the issue to me, and I will start working on it promptly.

**Comment by shreya024** [comment]
@s2sharpit Assigned!Go ahead

**Comment by s2sharpit** [comment]
Hey @shreya024 
I have raised PR corresponding to this issue.
Please review it.
