### ISSUE TITLE
[BUG] fix the navbar area

### ISSUE THREAD

**Issue by smty2018** [SrijanShovit/carbonops-v2#149]
fix the navbar area, the area is too big.
![Uploading image.png…]()

![image](https://github.com/SrijanShovit/carbonops-v2/assets/74114936/f002a734-3da4-42fd-a3b1-2d3b43c39f4e)

**Comment by SrijanShovit** [comment]
Hello smty2018, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Same as #47
