### ISSUE TITLE
Improvement: Optimize image paths for better maintainability

### ISSUE THREAD

**Issue by s2sharpit** [SrijanShovit/carbonops-v2#152]
Currently, the images in the code are imported and used directly, which can cause issues if the folder structure is modified. This makes it difficult to fetch the images correctly from the public folder. To improve maintainability and ensure consistent image retrieval, it is recommended to utilize Next.js' built-in support for relative paths relative to the public folder.

In this code snippet, I propose the following changes:

1. Update image imports to use absolute paths relative to the public folder.
2. Replace the imported images with their respective absolute paths.

These modifications will enhance the code's flexibility and make it more resilient to changes in the folder structure.

For example, In signup for organization page, it is implemented like this:
```
import welcomeImage from "../../../public/images/signup/welcome_img.png";
import emailIcon from "../../../public/icons/email.png";
import lockIcon from "../../../public/icons/lock.png";
import phoneIcon from "../../../public/icons/phone.png";
import contactIcon from "../../../public/icons/contact.png";
```
```
<Image src={welcomeImage} height={500} width={500} alt="Welcome to Carbonops" />
...
<Image src={emailIcon} width={30} height={30} alt="Email" />
...
<Image src={phoneIcon} width={30} height={30} alt="Contact" />
...
<Image src={cakeIcon} width={30} height={30} alt="Date of Birth" />
```

And the better way to implement this is to
Replace the imported images with their respective absolute paths
```
<Image src="/images/signup/welcome_img.png" height={500} width={500} alt="Welcome to Carbonops" />

<Image src="/icons/email.png" width={30} height={30} alt="Email" />

<Image src="/icons/phone.png" width={30} height={30} alt="Contact" />

<Image src="/icons/cake.png" width={30} height={30} alt="Date of Birth" />


```

Please assign the issue to me, and I will start working on it promptly.

**Comment by SrijanShovit** [comment]
Hello s2sharpit, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by s2sharpit** [comment]
Hey @shreya024 
ould you kindly review and merge this pull request as soon as possible if everything looks good? It would greatly assist me in proceeding with another issue, #148, as it addresses the problem I'm currently facing.
