### ISSUE TITLE
"Who we are?" Section Alignment Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [SrijanShovit/carbonops-v2#154]
The current design of this section is nice but it can be improved by making some alignment improvements. By working on the alignment of this content, I can make this section look even better.
**Current Alignment Design**
![carbonops (2)](https://github.com/SrijanShovit/carbonops-v2/assets/115794049/1c91aef2-d36f-4413-bdad-b105ab4667db)

**Expected Updated Alignment Design**
![carbonops (1)](https://github.com/SrijanShovit/carbonops-v2/assets/115794049/3b085bae-ed36-464a-86e9-4e4867bc1a4a)

**Comment by SrijanShovit** [comment]
Hello iamRabia-N, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Not Required
