### ISSUE TITLE
"SIGNUP" Text Color Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [SrijanShovit/carbonops-v2#155]
The current design of "SIGNUP" text is nice but it can be improved by changing the text color from blue to the green which is the theme color of the website and "SIGNUP" page. By changing the color, I can make this section look even better.

**Current Text Color**
![Carbonops (4)](https://github.com/SrijanShovit/carbonops-v2/assets/115794049/4e3551f5-bb03-4469-ac89-b0da47640f22)

**Expected Updated Text Color**
![Carbonops (3)](https://github.com/SrijanShovit/carbonops-v2/assets/115794049/72b50d33-d715-4fa0-8686-53575ffa4b0a)

**Comment by SrijanShovit** [comment]
Hello iamRabia-N, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
We can do this later
