### ISSUE TITLE
"LOGIN TO OUR PLATFORM" Text Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [SrijanShovit/carbonops-v2#156]
The current design of the this text is nice but this section can be improved by reducing the text from "LOGIN TO OUR PLATFORM" to "LOGIN". By reducing the text in this way, we can make this section look even better.

**Current Text**
![carbonops (6)](https://github.com/SrijanShovit/carbonops-v2/assets/115794049/3ec9818d-6e40-457e-95f8-312592253f3b)

**Expected Updated Text**
![carbonops (5)](https://github.com/SrijanShovit/carbonops-v2/assets/115794049/07721b9b-1dee-4338-84ae-03254467f40c)

**Comment by SrijanShovit** [comment]
Hello iamRabia-N, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Not required
