### ISSUE TITLE
Missing Issue Template in Repository

### ISSUE THREAD

**Issue by Nishitbaria** [SrijanShovit/carbonops-v2#16]
**Description:**

I noticed that the repository does not have an issue template. Having an issue template can greatly improve the clarity and consistency of issue reports, making it easier for contributors and maintainers to understand and address the problems or feature requests effectively.

**Comment by shreya024** [comment]
@Nishitbaria Assigned

**Comment by Nishitbaria** [comment]
Hey @shreya024 I have solve this problem You can See here Pull Request : https://github.com/SrijanShovit/carbonops-v2/pull/21#issue-1727159341

**Comment by Abhinavcode13** [comment]
is this issue open @shreya024

**Comment by shreya024** [comment]
> is this issue open @shreya024 

@Abhinavcode13 yup ,I have requested changes on the PR,but no responses yet.If u want u can start working on it

**Comment by Abhinavcode13** [comment]
Sure assign it to me ;) @shreya024

**Comment by Abhinavcode13** [comment]
Will make a PR in an hour ;)

**Comment by Abhinavcode13** [comment]
@shreya024 can it be level 3 I will add 3 other templates ;)

**Comment by Abhinavcode13** [comment]
Bug, new issue , doc_report

**Comment by Nishitbaria** [comment]
Hey @shreya024 My external exam is going that vice I am not able to do that sorry that
