### ISSUE TITLE
[Other] Image takes time on load

### ISSUE THREAD

**Issue by parasss19** [SrijanShovit/carbonops-v2#162]
## Current
- Images are .png format

## Change
- I will Convert Images in .webp format so that it will take less time on load
- It will also increase the performance of the website

**Comment by SrijanShovit** [comment]
Hello parasss19, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Not required
