### ISSUE TITLE
Navbar is not responsive

### ISSUE THREAD

**Issue by SubhamB2003** [SrijanShovit/carbonops-v2#166]
The current navbar is not responsive as well as it's not looking good. you can check below.
Please assign the issue to me under the GSSOC'23.

![image](https://github.com/SrijanShovit/carbonops-v2/assets/94003231/d725c096-fde5-43ee-9a58-a99e5e681078)

**Comment by SrijanShovit** [comment]
Hello SubhamB2003, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by SubhamB2003** [comment]
> Hello SubhamB2003, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.

Ok thank you

**Comment by karantec** [comment]
I am from GSSoC'23.
I would like to be assigned this task.
