### ISSUE TITLE
Add Contact Us page with Backend

### ISSUE THREAD

**Issue by AlfiyaSiddique** [SrijanShovit/carbonops-v2#167]
## Description
Currently, there is no contact us page on the website for user feedback. I want to completely implement this page from frontend to the backend.

For the frontend, I will add forms to receive user input and I will also handle the form data in the backend.
I will implement the validation for the contact form. I will make the page responsive and make the design similar to the other pages for consistency.

**According to me, the following fields should be there in the contact form:**
Name 
Email
Phone no.
Message or Issue

If you find this worth implementing then please assign me under gssoc label and let me know if you want to change anything mentioned above.

**Comment by SrijanShovit** [comment]
Hello AlfiyaSiddique, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
@AlfiyaSiddique Same as #33
