### ISSUE TITLE
Add Signup and login backend logic for Individual

### ISSUE THREAD

**Issue by AlfiyaSiddique** [SrijanShovit/carbonops-v2#168]
## Description
Currently, nothing happens when the user clicks on the signup button for the individual. I want to add the backend functionality where the user information gets stored in the database.

I will Add the proper routes in the backend for this function
I will Add the functions in the backend which will help to perform login and signup 
I will also link the frontend with the backend routes in the signup and login page.

## Request
If you find this worth implementing then please assign me this issue under gssoc label.

**Comment by SrijanShovit** [comment]
Hello AlfiyaSiddique, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
> ## Description
> Currently, nothing happens when the user clicks on the signup button for the individual. I want to add the backend functionality where the user information gets stored in the database.
> 
> I will Add the proper routes in the backend for this function I will Add the functions in the backend which will help to perform login and signup I will also link the frontend with the backend routes in the signup and login page.
> 
> ## Request
> If you find this worth implementing then please assign me this issue under gssoc label.

@AlfiyaSiddique Assigned ! Login with Google is working.Attach backend logic for SignUp with that logic and use nextAuth.

**Comment by AlfiyaSiddique** [comment]
> > ## Description
> > Currently, nothing happens when the user clicks on the signup button for the individual. I want to add the backend functionality where the user information gets stored in the database.
> > I will Add the proper routes in the backend for this function I will Add the functions in the backend which will help to perform login and signup I will also link the frontend with the backend routes in the signup and login page.
> > ## Request
> > If you find this worth implementing then please assign me this issue under gssoc label.
> 
> @AlfiyaSiddique Assigned ! Login with Google is working.Attach backend logic for **SignUp** with that logic and use nextAuth.

Hello @shreya024 

Here 👆🏻👆🏻
I guess you are saying to use nextAuth for Login with email. Because NextAuth isn't generally used for SignUp i.e. to register the user. For SignUp I can directly take user data and store it in the database properly. And for SignIn I should use NextAuth, Right?

Please resolve my doubt!!

**Comment by shreya024** [comment]
> > > ## Description
> > > Currently, nothing happens when the user clicks on the signup button for the individual. I want to add the backend functionality where the user information gets stored in the database.
> > > I will Add the proper routes in the backend for this function I will Add the functions in the backend which will help to perform login and signup I will also link the frontend with the backend routes in the signup and login page.
> > > ## Request
> > > If you find this worth implementing then please assign me this issue under gssoc label.
> > 
> > 
> > @AlfiyaSiddique Assigned ! Login with Google is working.Attach backend logic for **SignUp** with that logic and use nextAuth.
> 
> Hello @shreya024
> 
> Here 👆🏻👆🏻 I guess you are saying to use nextAuth for Login with email. Because NextAuth isn't generally used for SignUp i.e. to register the user. For SignUp I can directly take user data from form and store it in the database properly. And for SignIn I should use NextAuth, Right?
> 
> Please resolve my doubt!!

Okay yeah you are correct. @AlfiyaSiddique Go ahead! Write all backend logic in the backend folder
