### ISSUE TITLE
Issue: Fix navbar issue where about is also include in below navbar with active status.

### ISSUE THREAD

**Issue by Hareesh108** [SrijanShovit/carbonops-v2#169]
Below navbar do not have about option. It should be their.

![Screenshot from 2023-07-02 22-49-29](https://github.com/SrijanShovit/carbonops-v2/assets/72018706/397a2114-5e25-4665-9b05-db7125ec1479)

**Comment by SrijanShovit** [comment]
Hello Hareesh108, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Not Required
