### ISSUE TITLE
Add ContributingGuidelines.md

### ISSUE THREAD

**Issue by shanvijha30** [SrijanShovit/carbonops-v2#17]
The Contributing Guideline documentation will contain set of guidelines that will help contributors during the contribution process.
File type markdown.

**Comment by shreya024** [comment]
@shanvijha Assigned

**Comment by shreya024** [comment]
> @SrijanShovit Could you please assign this issue to me under GSSOC 23 Thank you!

Hey @shanvijha30 Any updates?

**Comment by shanvijha30** [comment]
@shreya024 Yes almost completed wil create a PR today.

**Comment by shanvijha30** [comment]
@shreya024 Added PR [#48](https://github.com/SrijanShovit/carbonops-v2/pull/48)
Please review it.
