### ISSUE TITLE
Issue: Login page is do not have proper alignment

### ISSUE THREAD

**Issue by Hareesh108** [SrijanShovit/carbonops-v2#170]
I want work on this issue. pls assign me

![Screenshot from 2023-07-02 22-54-29](https://github.com/SrijanShovit/carbonops-v2/assets/72018706/728808e5-bf7f-4027-bef2-8d4feeacff44)

**Comment by SrijanShovit** [comment]
Hello Hareesh108, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by karantec** [comment]
I am from GSSoC'23.
I would like to be assigned this task.

**Comment by Hareesh108** [comment]
Issue has been solved i am closing this issue. @shreya024
