### ISSUE TITLE
Add hover to the images of landing page

### ISSUE THREAD

**Issue by Akanksha-202** [SrijanShovit/carbonops-v2#175]
https://github.com/SrijanShovit/carbonops-v2/assets/100708686/b291f5f3-1130-41e5-86ac-5dd63913293f

Add this hiver effect to the static images of the website

Please assign this issue to me under GSSoC'23 label

**Comment by SrijanShovit** [comment]
Hello Akanksha-202, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Not required
