### ISSUE TITLE
The score keeps on adding up for a part when one changes their preference.

### ISSUE THREAD

**Issue by Akanksha-202** [SrijanShovit/carbonops-v2#177]
https://github.com/SrijanShovit/carbonops-v2/assets/100708686/51700051-e8cf-4fcc-bf99-b0dd2d10947f

I unchecked one option in the members part and checked another but instead of updating the score, it adds up!

Solution:
Giving a calculate(submit) button at the end when user is satisfied with all the choices and then take up all final values to calculate score!

Assign this issue to me under GSSoC'23 label:)

**Comment by SrijanShovit** [comment]
Hello Akanksha-202, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>
