### ISSUE TITLE
Bug : Spelling mistake in ReadMe file

### ISSUE THREAD

**Issue by accodes21** [SrijanShovit/carbonops-v2#178]
The spelling of audience is incorrect in the Project ReadMe file.

**Comment by SrijanShovit** [comment]
Hello accodes21, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by VishavSingla** [comment]
I had raised the pull request having solved the issue but it wasn't merged I don't know why.

**Comment by accodes21** [comment]
Oh I didn't know that, but since it's still not been solved ig the maintainers will assign it to someone in order to correct it.
