### ISSUE TITLE
Home Page UI Implementation

### ISSUE THREAD

**Issue by shreya024** [SrijanShovit/carbonops-v2#18]
## Description:
- Implement HomePage UI using NextUI/muI and Tailwind CSS according to the following design
- Make sure that the UI is fully responsive

## Design:
 
![HOME PAGE](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/c8554f58-60aa-4e89-9f96-622429bbbe13)

**Comment by MahendraDani** [comment]
@shreya024 I would like to work on this issue!
Would you please provide me with the assets used in the design (i.e images and logo)

**Comment by shreya024** [comment]
> @shreya024 I would like to work on this issue! Would you please provide me with the assets used in the design (i.e images and logo)

Sure @MahendraDani go ahead.You can find the images in unDraw
1.The world is mine
2.Things to say
3.Interview
4.My documents
5.Profile pic

Leave the graph area ,we will create another issue for that. Let me know if you need any other help

**Comment by MahendraDani** [comment]
@shreya024 Thank you so much for the input.
I will keep giving you the updates!

**Comment by MahendraDani** [comment]
@shreya024 I have already made a navbar as given in the above design.
Should I add the design suggested in #25 myself or let it be as it is?

**Comment by shreya024** [comment]
> @shreya024 I have already made a navbar as given in the above design. Should I add the design suggested in #25 myself or let it be as it is?

@MahendraDani Let it be as it is

**Comment by MahendraDani** [comment]
@shreya024 Alright!

**Comment by MahendraDani** [comment]
@shreya024 Currently I am done with the navbar, should I send you a video now or after finishing the entire homepage?
