### ISSUE TITLE
 Add Relevant Content to Homepage Instead of Placeholder Text

### ISSUE THREAD

**Issue by Nishitbaria** [SrijanShovit/carbonops-v2#187]
###  **Description:**

**Currently, the homepage of our project's GitHub repository is populated with generic placeholder text (lorem ipsum) that does not provide any meaningful information to visitors. It is crucial to enhance the user experience by replacing this placeholder content with relevant and engaging information.**

### **Expected Behavior:**

**The homepage should display relevant content that accurately represents the project, its purpose, and its current status. This will give potential users and contributors a better understanding of what the project entails and how they can get involved.**

![image](https://github.com/SrijanShovit/carbonops-v2/assets/85815172/eb93a7f2-793a-4c51-a433-fcead0c43246)

**Comment by SrijanShovit** [comment]
Hello Nishitbaria, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Not required
