### ISSUE TITLE
Selecting  option in one parameter erases selected option in another parameter in Carbon Calculator

### ISSUE THREAD

**Issue by Nishitbaria** [SrijanShovit/carbonops-v2#188]
Description:
Currently, there is an issue in the Carbon Calculator application where selecting an option in one parameter section unintentionally erases the selected option in another parameter section. This behavior is not desired and causes confusion and inconvenience for users when trying to calculate their carbon footprint accurately. 

Steps to Reproduce:
1. Open the Carbon Calculator application.
2. Navigate to the parameter section where multiple options are available (e.g., "House").
3. Select an option from this section (e.g., "Members"->"you live alone").
4. Now, navigate to another parameter section (e.g., "House-size").
5. Select an option from this section (e.g., " you have a large house").
6. Observe that the previously selected option in the "Members" section has been erased and reverted to the default or unselected state.

Expected Behavior:
When selecting an option in one parameter section, the selected options in other parameter sections should remain unaffected and unchanged. The user's selections should persist throughout the calculation process, allowing them to accurately assess their carbon footprint based on multiple factors.

Actual Behavior:
The selection of an option in one parameter section unintentionally erases the selected options in other parameter sections, leading to an inaccurate representation of the user's input and carbon footprint calculation.

Impact:
- User frustration and confusion due to unexpected behavior.
- Inaccurate carbon footprint calculations as users are unable to select options across different parameters simultaneously.

Suggested Solution:
Implement a fix that allows users to select options independently in each parameter section without erasing selections made in other sections. The application should retain the user's chosen options throughout the calculation process, providing an accurate assessment of their carbon footprint based on the combined inputs from multiple parameters.

This issue significantly affects the usability and reliability of the Carbon Calculator website. Resolving this problem will greatly improve the user experience and ensure accurate carbon footprint calculations.

please see this **video** :

[Video](https://github.com/Nishitdev/Vite-ReactApp/assets/123718275/cf7a9127-1721-4085-a891-bcdc44f6ca64)

Please assign me this issue ,I will create pull request asap.

**Comment by SrijanShovit** [comment]
Hello Nishitbaria, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by Nishitbaria** [comment]
@SrijanShovit ,please assign me this issue

**Comment by Nishitbaria** [comment]
@SrijanShovit ,please assign me this issue

**Comment by Nishitbaria** [comment]
@shreya024 ,please assign me this issue
