### ISSUE TITLE
Feat: Create Issue buttons and their forms respectively .

### ISSUE THREAD

**Issue by dakshsinghrathore** [SrijanShovit/carbonops-v2#189]
Currently the contributor has to raise an issue from ground zero without any ***prebuilt buttons***, to gain a better understanding of the issue raised we can create custom issue buttons which will be ***visually appealing*** as well ***hassle free*** for the contributor to express their concern in an ***ordered manner*** .
 Here 👇 are some screenshots attached to give you a better understanding on what am up to
### Currently 

![Screenshot 2023-06-13 at 23-14-43 New Issue · SrijanShovit_carbonops-v2](https://github.com/SrijanShovit/carbonops-v2/assets/115932772/66a1f488-b745-4124-a218-92bbbc7307ef)

### To Come

![Screenshot 2023-06-13 at 23-19-39 New Issue · priyankarpal_ProjectsHut](https://github.com/SrijanShovit/carbonops-v2/assets/115932772/42addc33-f9fb-4eaf-b60a-fb7dab74844c)

I would also like to add respective issue forms to every button, it will be easy for the contributor to raise an issue also it will be visually pleasing for the admin to go through the issue hassle free. 👇

![Screenshot 2023-06-23 at 21-22-39 New Issue · dakshsinghrathore_htmltut](https://github.com/roshan1337d/coding-contests-companion/assets/115932772/82936b04-6272-4660-b3e7-38eb5728d6b0)

**Comment by SrijanShovit** [comment]
Hello dakshsinghrathore, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by dakshsinghrathore** [comment]
Kindly assign this issue to me @SrijanShovit

**Comment by karantec** [comment]
I am from GSSoC'23.
I would like to be assigned this task.

**Comment by shreya024** [comment]
Not required
