### ISSUE TITLE
SignUp UI Implementation

### ISSUE THREAD

**Issue by shreya024** [SrijanShovit/carbonops-v2#19]
## Description:
- Implement SignUp UI using NextUI or Material UI (mui) and Tailwind CSS according to the following design
- On Clicking the SignUp button on HomePage,a popup will open where user can select whether to signup as an individual or organization
- On Clicking SignUp As an Individual/Sign Up as an Organization, conditionally render respective forms
- Make sure that the UI is fully responsive

## Design:
 
![SignUP PopUP](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/e2527c9e-5433-4cef-8f8d-754305df4e75) | 
![SignUp-Organisation](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/239d2b32-38ad-4c1d-b65d-2458e785450f) |
![SignUp-Individual](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/8b32b2ab-c658-4851-8e0d-57d16481c194)

**Comment by MahendraDani** [comment]
@shreya024 I would like to work on this issue.
Please provide me with the images used in the design.
Thanks!

**Comment by MahendraDani** [comment]
@shreya024 I have already developed the home page. I can complete this issue if your would please assign this to me!

Please provide the resources for all the images,logo,etc.

Thanks

**Comment by shreya024** [comment]
> @shreya024 I have already developed the home page. I can complete this issue if your would please assign this to me!
> 
> Please provide the resources for all the images,logo,etc.
> 
> Thanks

@MahendraDani Sure go ahead!. Resources are :
1.
![image](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/55a7310f-19a0-4407-b161-430312baca05)
2.
![image](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/0b72a8f2-dfbb-4a1b-a157-0755735f6614)
3.Undraw Welcome

Let me know if you need any other resource

**Comment by MahendraDani** [comment]
@shreya024 I have a doubt:
Should I create the `signup page` in the same branch through which I have raised PR for the `homepage`?
Because we will have to route the `signup page` from the `signup button` in navbar of homepage of the website.

Or should I create a different branch and make the `signup page` and later we can route the pages when both the PRs will be merged?

**Comment by MahendraDani** [comment]
@shreya024 Would you please provide the resources for the logos used in signup form in the above designs?
Thanks!

**Comment by shreya024** [comment]
> @shreya024 I have a doubt: Should I create the `signup page` in the same branch through which I have raised PR for the `homepage`? Because we will have to route the `signup page` from the `signup button` in navbar of homepage of the website.
> 
> Or should I create a different branch and make the `signup page` and later we can route the pages when both the PRs will be merged?

@MahendraDani Take a pull and then continue on the same branch or create a new branch (whichever suits you)

**Comment by shreya024** [comment]
> @shreya024 Would you please provide the resources for the logos used in signup form in the above designs? Thanks!

@MahendraDani Sure,you can get them from Iconly free icons

**Comment by MahendraDani** [comment]
@shreya024 Thanks a lot.
Will try to complete it in a day or two!

**Comment by shreya024** [comment]
> @shreya024 Thanks a lot. Will try to complete it in a day or two!

@MahendraDani Ok no problem. Also add `if (typeof window !== "undefined")` before line 20 in Navbar.js in your next PR

**Comment by MahendraDani** [comment]
> @MahendraDani Ok no problem. Also add `if (typeof window !== "undefined")` before line 20 in Navbar.js in your next PR

Sure!
