### ISSUE TITLE
Bug: Checkbox button not getting checked while clicking the corresponding text 

### ISSUE THREAD

**Issue by dakshsinghrathore** [SrijanShovit/carbonops-v2#190]
The remember me checkbox button is not working upon click on the text. I will fix this issue, kindly assign this issue to me @SrijanShovit  

![Screenshot 2023-07-05 at 15-32-21 Carbonops](https://github.com/SrijanShovit/carbonops-v2/assets/115932772/6eac5b07-4995-499b-96fd-4de0399ec58a)

**Comment by SrijanShovit** [comment]
Hello dakshsinghrathore, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>
