### ISSUE TITLE
Login UI Implementation

### ISSUE THREAD

**Issue by shreya024** [SrijanShovit/carbonops-v2#20]
## Description:
- Implement LogIn UI using NextUI or Material UI (mui) and Tailwind CSS according to the following design
- On Clicking the Login button on HomePage, Login page will open
- Make sure that the UI is fully responsive

## Design:
![loginpage](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/f203f705-fa01-4c4b-a2b9-79e03ab41ca8)

**Comment by MahendraDani** [comment]
@shreya024 I would like to work on this issue!
Please provide the images used in the design!
Thanks!

**Comment by MahendraDani** [comment]
@shreya024 I have developed the homepage for the website.
I can complete this issue if you would assign this to me.

Please provide the resources of all images.logos,etc.

Thanks!

**Comment by MahendraDani** [comment]
@shreya024 I have created the `Signup pages` for the website and raised the PR for the same.
Please assign me this issue!
Thanks!

**Comment by MahendraDani** [comment]
@shreya024 mam,
Thank you for assigining me this issue.

Would you please provide the image used in the above design.
Thanks!

**Comment by shreya024** [comment]
> @shreya024 mam,
> Thank you for assigning me this issue.
> 
> Would you please provide the image used in the above design?
> Thanks!

@MahendraDani the image used in this is unDraw Environment

**Comment by MahendraDani** [comment]
@shreya024 I will try to complete this issue within 2-3 days.
Will it be fine?

**Comment by shreya024** [comment]
> @shreya024 I will try to complete this issue within 2-3 days.
> Will it be fine?

Yeah sure
