### ISSUE TITLE
New UI for carbon footprint calculator

### ISSUE THREAD

**Issue by Vanoita** [SrijanShovit/carbonops-v2#209]
The webpage appears blank, and the method of clicking on the text to access a dropdown box feels confusing and counterintuitive. It would be more intuitive to have a dedicated dropdown box alongside the text to enhance user-friendliness.

**Comment by SrijanShovit** [comment]
Hello Vanoita, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Not required
