### ISSUE TITLE
Add table of contents to readme

### ISSUE THREAD

**Issue by Vanoita** [SrijanShovit/carbonops-v2#210]
To enhance the organization and accessibility of the README file, I want to include a table of contents. A table of contents provides an overview of the sections or topics covered in the document, allowing readers to quickly navigate to the specific information they need.

**Comment by SrijanShovit** [comment]
Hello Vanoita, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Not required
