### ISSUE TITLE
Want to add hover effect on the social icons

### ISSUE THREAD

**Issue by HimanshuNarware** [SrijanShovit/carbonops-v2#214]
##
Description
I want to add hover effect on the navbar social icons
##Screenshot
![68](https://github.com/SrijanShovit/carbonops-v2/assets/83147410/0c2ac408-0b94-491c-a766-cd7a004f9a04)

**Comment by SrijanShovit** [comment]
Hello HimanshuNarware, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>
