### ISSUE TITLE
Contributor page ui improvement

### ISSUE THREAD

**Issue by SubhamB2003** [SrijanShovit/carbonops-v2#216]
Hey, I want to add more fields on the contributor page and also change the UI. 
Can you please assign it to me

**Comment by SrijanShovit** [comment]
Hello SubhamB2003, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
UI Changes are not required.We are focusing more on the functionality part
