### ISSUE TITLE
 Implement MVC Folder Structure and Schema for Carbonops Backend

### ISSUE THREAD

**Issue by Nishitbaria** [SrijanShovit/carbonops-v2#22]
`Description:`

I would like to propose the implementation of an MVC (Model-View-Controller) folder structure and the creation of a schema for the Carbonops project's backend. The current project lacks a standardized organization of files and folders, which hampers code maintainability and scalability. Additionally, there is a need for a well-defined schema to ensure efficient data management and retrieval.

`Objective:`

The objective of this issue is to establish an organized folder structure following the MVC architectural pattern and create a schema for the Carbonops backend. These enhancements will enhance code modularity, readability, and the overall maintainability of the project. Additionally, the schema will provide a structured framework for managing and querying 

`Benefits:`

By implementing an MVC folder structure and creating a schema for the Carbonops backend, the project will gain the following benefits:

- Improved Code Organization: The MVC folder structure will promote a modular and organized codebase, enhancing code readability and maintainability.

- Separation of Concerns: Clear separation of models, views, and controllers will facilitate better code management and future enhancements.

- Scalability: The organized structure will allow for easier integration of new features and components, enabling the project to scale effectively.

- Efficient Data Management: The schema will provide a structured framework for storing and querying environmental data, ensuring optimal data management and retrieval.

**Comment by shreya024** [comment]
Hey @Nishitbaria thank you for the issue.We are planning on changing the existing ER Diagram a bit.As soon as that is done,we will assign this issue to you :)

**Comment by shreya024** [comment]
@Nishitbaria Assigned.Take reference from the ER Diagram in PR #76

**Comment by Nishitbaria** [comment]
Till tomorrow I will Create @shreya024

**Comment by shreya024** [comment]
> Till tomorrow I will Create @shreya024

@Nishitbaria Any updates?

**Comment by Nishitbaria** [comment]
@shreya024 All Most done I will Create in Few Min

**Comment by rick711c** [comment]
I want to work on this issue

**Comment by shreya024** [comment]
> I want to work on this issue 

Assigned! Go ahead

**Comment by shreya024** [comment]
Reopening as not yet completed. @Nishitbaria Don't close issues

**Comment by suzy-g38** [comment]
If nobody is working on it can I work on it?

> Reopening as not yet completed. @Nishitbaria Don't close issues
