### ISSUE TITLE
Streamlining page layout with a global navbar and footer

### ISSUE THREAD

**Issue by BhavinRaichura** [SrijanShovit/carbonops-v2#221]
**Issue Overview:**
The current state of the project requires the addition of a navbar and footer on every page, which can be time-consuming and error-prone. I propose a significant improvement to the project by implementing a more efficient and consistent approach to handling the layout across all pages.

**Proposed Solution:**
To address this issue, my proposal involves making alterations to the _layout.js_ file. By doing so, we can establish a global layout that automatically includes the navbar and footer on every page. This enhancement will simplify the development process, enhance code maintainability, and ensure a unified user experience throughout the entire website.

**Expected Changes:**
Refactor the _layout.js_ file to include the navbar and footer components, so they are consistently rendered across all pages without manual additions.

**I would like to work on this issue please assign it to me**

**Comment by SrijanShovit** [comment]
Hello BhavinRaichura, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by LaxmanSingh07** [comment]
hey @shreya024  is this issue has resolved?
if not, Please Assign me the task under GSSOC'23. I am eager to work on it.

**Comment by shreya024** [comment]
@BhavinRaichura Any updates?

**Comment by BhavinRaichura** [comment]
> @BhavinRaichura Any updates?
Sorry for the delay i have finished my work
