### ISSUE TITLE
Fix the login page - BUG

### ISSUE THREAD

**Issue by akanksha984** [SrijanShovit/carbonops-v2#226]
Even on no input the user gets logged In. I want to fix this bug. Please assign it to me under gssoc'23

**Comment by SrijanShovit** [comment]
Hello akanksha984, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by akanksha984** [comment]
@shreya024 please assign this to me

**Comment by shreya024** [comment]
Not required.
