### ISSUE TITLE
Fix some minor bugs in login form

### ISSUE THREAD

**Issue by akanksha984** [SrijanShovit/carbonops-v2#228]
![image](https://github.com/SrijanShovit/carbonops-v2/assets/97845909/80ae7267-c1d0-4e02-845f-290bc7ba1e81)

I want to improve the spacing and the buttons, also the show password does not convert to cursor on hover.
I would like to fix these minor bugs.
Please assign it to me under gssoc'23

**Comment by SrijanShovit** [comment]
Hello akanksha984, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>
