### ISSUE TITLE
Add Home button in calculate page

### ISSUE THREAD

**Issue by pavitrachavda97** [SrijanShovit/carbonops-v2#229]
It is good if you add home button which redirect to home page of website to make website effective and easy to redirect.
I want to add home button at circled area.
![image](https://github.com/SrijanShovit/carbonops-v2/assets/91004608/966b1b45-432a-4b1e-b165-bce78aafbb88)

I want to work on this issue.
Assign this issue to me under GSSOC'23

**Comment by SrijanShovit** [comment]
Hello pavitrachavda97, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>
