### ISSUE TITLE
[Enhancement] Adding URL in the image itself and Enhancing UI of About us section

### ISSUE THREAD

**Issue by Anshika-Jain02** [SrijanShovit/carbonops-v2#24]
*The placards in the About Us section are looking non-appealing. we can add the LinkedIn link of the team members in the image itself to increase user convenience as when the person will click anywhere in the image it will take him/her to the respective LinkedIn page*

*We can also enhance the UI of this section by adding hovering effects on various placards and enhancing the font style*

**Please assign this issue to me under Gssoc'23 @SrijanShovit**

![carbonops](https://github.com/SrijanShovit/carbonops-v2/assets/104912087/6093ffff-cd11-4325-97f4-724b4f9d04cb)

**Comment by shreya024** [comment]
@Anshika-Jain02 I think the About Us is not yet implemented.Are you ok working on the UI Implementation of this page using Next UI/MUI with tailwind css?

**Comment by SrijanShovit** [comment]
In case About us is implemented for this repo, I would like to include all buddies contributing here to be listed and not old ones.

**Comment by Anshika-Jain02** [comment]
Yes ma'am I would love to work on this but as my exams are approaching next week can you please give me some more time than usual to complete the whole task. Till then, I can resolve the issue that I stated if you are ok with this @shreya024

**Comment by shreya024** [comment]
> Yes ma'am I would love to work on this but as my exams are approaching next week so, can you please give me some more time than usual to complete the whole task. Till then, I can resolve the issue that I stated if you are ok with this @shreya024

@Anshika-Jain02 Ok sure. Go ahead!

**Comment by Anshika-Jain02** [comment]
so, should I create a new issue regarding the whole UI of the About Us section and solve the part that I have discussed for this issue for now or should I submit the whole work together later on

**Comment by shreya024** [comment]
> so, should I create a new issue regarding the whole UI of the About Us section and solve the part that I have discussed for this issue for now or should I submit the whole work together later on @shreya024

Hey @Anshika-Jain02,I have created #30 for that,you can contribute to any of the issues,whichever you are comfortable with :)

**Comment by Anshika-Jain02** [comment]
Ma'am as there is another repo link in this repo in which the deployed website link is working so, should I create a clone of the other repo and send the PR request there?

**Comment by Anshika-Jain02** [comment]
*@shreya024 ma'am these are some of the changes that I have made till now. I need links of the LinkedIn profile of all the teammates so, that people can navigate to their profiles by clicking on their respective containers. Also, I have created an extra teammate container to make it look consistent so, I need the required data for that too*

*Can you please help me asap and please suggest if you require any more changes*

https://github.com/SrijanShovit/carbonops-v2/assets/104912087/2ca00978-7d28-4ed7-88fe-c88ef9451541

**Comment by shreya024** [comment]
> *@shreya024 ma'am these are some of the changes that I have made till now. I need links of the LinkedIn profile of all the teammates so, that people can navigate to their profiles by clicking on their respective containers. Also, I have created an extra teammate container to make it look consistent so, I need the required data for that too*
> 
> *Can you please help me asap and please suggest if you require any more changes*
> 
> https://github.com/SrijanShovit/carbonops-v2/assets/104912087/2ca00978-7d28-4ed7-88fe-c88ef9451541
> 
> 

Hey @Anshika-Jain02 make a PR.We are planning on populating the data dynamically with the help of Github API.

**Comment by shreya024** [comment]
@Anshika-Jain02 You can take a pull and start making changes now.About Us PR is merged

**Comment by shreya024** [comment]
@Anshika-Jain02 Any updates?
