### ISSUE TITLE
[Feature] Adding navbar 

### ISSUE THREAD

**Issue by DivyanshiNarang** [SrijanShovit/carbonops-v2#25]
Current:
<img width="947" alt="Screenshot 2023-05-27 000032" src="https://github.com/SrijanShovit/carbonops-v2/assets/74779601/ad8b78d7-4285-4601-b30f-94653fb1cc01">

Solution:
We can add a navbar to help the user browse through the website effortlessly.

Sample:
![HOME](https://github.com/SrijanShovit/carbonops-v2/assets/74779601/229f5362-306e-43f6-b707-4f0db23b2dd1)

*Please assign this to me under GSSoC'23* @SrijanShovit

**Comment by shreya024** [comment]
@DivyanshiNarang Kindly wait till PR for #18 is merged, and then start working on this

**Comment by DivyanshiNarang** [comment]
Can I start working on this now? @shreya024

**Comment by shreya024** [comment]
> Can I start working on this now? @shreya024

@DivyanshiNarang Sure.Go Ahead!

**Comment by shreya024** [comment]
@DivyanshiNarang Any updates?

**Comment by parasss19** [comment]
Hi @shreya024 can i work on this issue as i have already experience in this part.

**Comment by Abhinavcode13** [comment]
@shreya024 what's update on this?

**Comment by shreya024** [comment]
@DivyanshiNarang How much more time do you need?
