### ISSUE TITLE
Carbon FootPrint Calculator UI Implementation

### ISSUE THREAD

**Issue by shreya024** [SrijanShovit/carbonops-v2#32]
## Description:
- Implement Carbon Footprint Caalculator UI using NextUI or Material UI (mui) and Tailwind CSS according to the following design
- On Clicking the Calculate button on HomePage,this page will open,only if user is signed in
- Make sure that the UI is fully responsive

## Design:
![image](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/12985ed2-bca6-44b5-b3a7-189a099ed429)

**Comment by MahendraDani** [comment]
@shreya024 I would like to work on this issue!
