### ISSUE TITLE
Contact US UI Implementation

### ISSUE THREAD

**Issue by shreya024** [SrijanShovit/carbonops-v2#33]
## Description:
- Implement Contact Us UI using NextUI or Material UI (mui) and Tailwind CSS according to the following design
- On Clicking the Contact Us button on HomePage,this page will open
- Make sure that the UI is fully responsive

## Design:
![Contact us and feedback page](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/43c78f3d-e68f-4dde-bd9f-eb543bdc0896)

**Comment by Anshika-Jain02** [comment]
Ma'am is it assigned to someone or i can work on this?

**Comment by shreya024** [comment]
> Ma'am is it assigned to someone or i can work on this?

Not assigned to anyone yet.Would u like to work on it?

**Comment by Anshika-Jain02** [comment]
Yes ma'am please assign it to me

**Comment by shreya024** [comment]
> Yes ma'am please assign it to me

@Anshika-Jain02 Any updates?

**Comment by Anshika-Jain02** [comment]
@shreya024  Ma'am actually my end-semester exams are going on due to which I need some more time than usual. Also, I am facing some issues while linking so, waiting for some merge that has solved this problem in order to get some idea regarding my issue.

**Comment by shreya024** [comment]
> @shreya024  Ma'am actually my end-semester exams are going on due to which I need some more time than usual. Also, I am facing some issues while linking so, waiting for some merge that has solved this problem in order to get some idea regarding my issue.

You can get idea about linking from the already merged login and signup pages

**Comment by Anshika-Jain02** [comment]
Ok ma'am @shreya024

**Comment by shreya024** [comment]
> @Abhinavcode13 I am working on this issue. You can search another one.

@Anshika-Jain02 How much more time do you need?

**Comment by Anshika-Jain02** [comment]
@shreya024 Sorry for the delay. Ma'am i just need two more days if possible.

**Comment by shreya024** [comment]
> @shreya024 Sorry for the delay. Ma'am i just need two more days if possible.

@Anshika-Jain02 Any updates?

**Comment by shreya024** [comment]
@Anshika-Jain02 Reassigning issue to @Abhinavcode13 for time constraints. @Abhinavcode13 Assigned. Go ahead!

**Comment by Anshika-Jain02** [comment]
> @Anshika-Jain02 Reassigning issue to @Abhinavcode13 for time constraints. @Abhinavcode13 Assigned. Go ahead!

@shreya024 Sorry ma'am for the delay. I was sick from the past few days and hence, I was not able to finish this task. I will take care of this in the rest of my issues. @Abhinavcode13 please let me know if you need any guidance as I have completed some of the work on this so, I can help you if you get stuck anywhere.

**Comment by Abhinavcode13** [comment]
@Anshika-Jain02 nevermind wanna take this up?
if you have already started.

**Comment by shreya024** [comment]
@Abhinavcode13 Any updates?

**Comment by Abhinavcode13** [comment]
i have made the page but how to link it to main home page @shreya024 ?

**Comment by shreya024** [comment]
> i have made the page but how to link it to main home page @shreya024 ?

You can route the page to /contactus and it will open on clicking Contact button in Navbar

**Comment by Abhinavcode13** [comment]
fine wait @shreya024

**Comment by Abhinavcode13** [comment]
where is the html file? @shreya024

**Comment by shreya024** [comment]
> where is the html file? @shreya024

This is a next project.Routing is defined by the folder structure.

**Comment by shreya024** [comment]
@Abhinavcode13 Any updates?

**Comment by Soulpurr** [comment]
@shreya024 can I work on this?

**Comment by shreya024** [comment]
@Abhinavcode13 make a valid PR else issue will be reassigned

**Comment by shreya024** [comment]
> @Abhinavcode13 make a valid PR by tomorrow else issue will be reassigned

**Comment by Soulpurr** [comment]
> @Abhinavcode13 make a valid PR by tomorrow else issue will be reassigned

assign this to me incase he fails to make a valid pr

**Comment by Soulpurr** [comment]
Will do it as soon as possible meanwhile pls review #134

**Comment by Soulpurr** [comment]
> @Soulpurr Any updates?

Sorry I have my end sem going on but I will do it by almost tomorrow night.
