### ISSUE TITLE
[Docs] Missing .env.example file.

### ISSUE THREAD

**Issue by Anshika-Jain02** [SrijanShovit/carbonops-v2#36]
*According to the guidelines while setting up this project for ourselves we have to do the following :*
**"Set up a .env file**
**Add relevant credentials in the .env file with the help of .env.example file."**
*but the .env.example file is missing from this repo so, I can add it.*

*Please assign me this issue under Gssoc'23 @shreya024*

**Comment by shreya024** [comment]
@Anshika-Jain02 Kindly work on the issues already assigned.Currently the project can run without the .env file
