### ISSUE TITLE
Login and SignUp links are not working for Mobile Navmenu

### ISSUE THREAD

**Issue by Akash-gahlot** [SrijanShovit/carbonops-v2#39]
@shreya024  there is a minor issue in code , Login and SignUp links are not redirecting to login and Signup pages for the Mobile NavMenu ,  small code changes are required .
Can i fix this issue?

**Comment by shreya024** [comment]
Sure @Akash-gahlot

**Comment by Akash-gahlot** [comment]
https://github.com/SrijanShovit/carbonops-v2/assets/71133465/7e01795d-45a9-4597-b8e7-4fa35fc8491a

#40 - The issue has been has been fixed and created pull request.
