### ISSUE TITLE
Login Using OAuth

### ISSUE THREAD

**Issue by Deepanshu0703** [SrijanShovit/carbonops-v2#42]
As I have seen tehre is no sign in option using google so i wanna work on this thing. We can avail this facility using Firebase. So do assign it to me .

**Comment by Deepanshu0703** [comment]
Also I want tp make backend for existing signUp and signin options

**Comment by shreya024** [comment]
> As I have seen tehre is no sign in option using google so i wanna work on this thing. We can avail this facility using Firebase. So do assign it to me .

@Deepanshu0703 We want the Google Sign In Feature using OAuth.Let me know if you are still interested

**Comment by shreya024** [comment]
> Also I want tp make backend for existing signUp and signin options

We will soon create issues on this once we figure out the modified ER Diagram

**Comment by Deepanshu0703** [comment]
> > As I have seen tehre is no sign in option using google so i wanna work on this thing. We can avail this facility using Firebase. So do assign it to me .
> 
> @Deepanshu0703 We want the Google Sign In Feature using OAuth.Let me know if you are still interested

Ok I can do that too

**Comment by shreya024** [comment]
@Deepanshu0703 Assigned.Implement login using OAuth

**Comment by Deepanshu0703** [comment]
Thanks for assigning it to me , I will add this feature and provide the sample of credentials needed in example.env format

**Comment by shreya024** [comment]
> Thanks for assigning it to me , I will add this feature and provide the sample of credentials needed in example.env format

@Deepanshu0703 Any updates?

**Comment by shreya024** [comment]
> Hi @shreya024 i am too interested in doing it through OAuth and storing the details of user in database too..

Okay @AKsHaT123456A Reassigning to you

**Comment by suzy-g38** [comment]
I would like to work on this issue.

**Comment by AKsHaT123456A** [comment]
Hi @shreya024 but i started working on it

**Comment by shreya024** [comment]
> I would like to work on this issue.

@suzy-g38 updates?

**Comment by Ja3mamtora** [comment]
It is not done yet may i take over this task ?
