### ISSUE TITLE
Github API Integration

### ISSUE THREAD

**Issue by shreya024** [SrijanShovit/carbonops-v2#44]
## Description:
- In the About Us,render details of contributors of this repo
- Use [this Github API](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repository-contributors) to fetch the data
- On clicking,it will redirect to that contributor's github profile

**Comment by Ida-Naliaka** [comment]
Can I work on this issue once the UI is done?

**Comment by shreya024** [comment]
> Can I work on this issue once the UI is done?

@Ida-Naliaka Sure.Go ahead!

**Comment by Akash-gahlot** [comment]
Hi @shreya024  the issue has been solved or not ?
if not could you please assign it to me I will fix it asap.
