### ISSUE TITLE
[BUG] : Link not working

### ISSUE THREAD

**Issue by Abhinavcode13** [SrijanShovit/carbonops-v2#45]
ER diagram link provided is not working and directs to 404 error.

screenshot:
![image](https://github.com/SrijanShovit/carbonops-v2/assets/126642111/45e51260-3d14-47be-85ee-5935b7617427)

**Comment by Abhinavcode13** [comment]
Please assign this issue under gssoc 23 @shreya024

**Comment by shreya024** [comment]
It's ok,we are going to modify the ER Diagram anyway and update it soon
