### ISSUE TITLE
ER Diagram Modification

### ISSUE THREAD

**Issue by shreya024** [SrijanShovit/carbonops-v2#54]
## Description:
- Make a copy of the existing ER Diagram in [Whimsical](https://whimsical.com/) and modify it w.r.t following instructions
- Create a new entity called SignUp with the attributes
  - Role (Individual/Organization)
  - Name
  - Email 
  - Password (OAuth)
  - Aadhar Number(optional if Role is Individual)
  - Org. License ID (if Role is Organization)
 
- Replace Existing Entity named Individual with Individual Profile Completion
  - Profile Image
  - D.O.B
  - City
  - Occupation Type
  - Social Media Links
  - Address
 
- Replace Existing Entity named Organization with Organization Profile Completion
  - Contact No.
  - Location
  - Waste Requirements
  - Website
  - Social Media Links
  - Type of Organization
  - Product Deals

- Create relation from Signup Entity(Individual/Org MongoDB id as PK) to Individual Profile Completion & Organization Profile Completion via Individual/Org MongoDB id as FK

## Previous ER Diagram
![WhatsApp Image 2023-05-29 at 14 37 38](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/b0a63da7-0f18-4698-980d-c097900f0c99)

**Comment by MahendraDani** [comment]
@shreya024 I would like to work on this issue!

**Comment by MahendraDani** [comment]
@shreya024 
I am almost done with the ER diagram, just have to join each enitity via PK and FK.
Please checkout the [ER diagram](https://lucid.app/lucidchart/ccff0196-6408-437e-9210-d7a222d7c0e5/edit?viewport_loc=147%2C548%2C1792%2C800%2C0_0&invitationId=inv_4c39b0f5-c7c4-4942-9740-5e5d83352291).
Please review the diagram and let me know if there are any changes.

P.S : How should I raise PR for it? Should I add the diagram in the `README.md` file?

Thanks

**Comment by shreya024** [comment]
> @shreya024 I am almost done with the ER diagram, just have to join each enitity via PK and FK. Please checkout the [ER diagram](https://lucid.app/lucidchart/ccff0196-6408-437e-9210-d7a222d7c0e5/edit?viewport_loc=147%2C548%2C1792%2C800%2C0_0&invitationId=inv_4c39b0f5-c7c4-4942-9740-5e5d83352291). Please review the diagram and let me know if there are any changes.
> 
> P.S : How should I raise PR for it? Should I add the diagram in the `README.md` file?
> 
> Thanks

@MahendraDani Place Sign Up in the beginning.The workflow begins from there.Make sure the attributes of Individual Profile Completion are as it is as mentioned in the comment above.And join the entities with proper relations and PK/FK. You can upload the ER Diagram.png to the repo and add a relative link to it in the README.

**Comment by shreya024** [comment]
> > @shreya024 I am almost done with the ER diagram, just have to join each enitity via PK and FK. Please checkout the [ER diagram](https://lucid.app/lucidchart/ccff0196-6408-437e-9210-d7a222d7c0e5/edit?viewport_loc=147%2C548%2C1792%2C800%2C0_0&invitationId=inv_4c39b0f5-c7c4-4942-9740-5e5d83352291). Please review the diagram and let me know if there are any changes.
> > P.S : How should I raise PR for it? Should I add the diagram in the `README.md` file?
> > Thanks
> 
> @MahendraDani Place Sign Up in the beginning.The workflow begins from there.Make sure the attributes of Individual/Org Profile Completion are as it is as mentioned in the comment above.And join the entities with proper relations and PK/FK. You can upload the ER Diagram.png to the repo and add a relative link to it in the README.
