### ISSUE TITLE
Add depandabot 

### ISSUE THREAD

**Issue by k-deepak04** [SrijanShovit/carbonops-v2#58]
"Integrating Dependabot into our open-source project will automate dependency updates, ensuring we stay up-to-date with the latest security patches and feature enhancements."
"By leveraging Dependabot's automated pull requests for dependency updates, we can reduce the burden on maintainers and foster a more secure and stable codebase."
"Adding Dependabot as a dependency management tool will demonstrate our commitment to maintaining a healthy ecosystem, allowing contributors to focus on higher-value tasks while keeping our project dependencies secure and reliable."

![image](https://github.com/SrijanShovit/carbonops-v2/assets/96341431/34647d87-a0c2-4fdb-8d83-a385beb0ef9b)

**Comment by shreya024** [comment]
![Screenshot_20230602-102803_GitHub.jpg](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/204e0ba6-8635-4cdf-a08b-311e935beeff)

Replace EddieHubCommunity with this repo  in previous and this issue as well

**Comment by shreya024** [comment]
> "Integrating Dependabot into our open-source project will automate dependency updates, ensuring we stay up-to-date with the latest security patches and feature enhancements."
> "By leveraging Dependabot's automated pull requests for dependency updates, we can reduce the burden on maintainers and foster a more secure and stable codebase."
> "Adding Dependabot as a dependency management tool will demonstrate our commitment to maintaining a healthy ecosystem, allowing contributors to focus on higher-value tasks while keeping our project dependencies secure and reliable."
> 
> ![image](https://github.com/SrijanShovit/carbonops-v2/assets/96341431/34647d87-a0c2-4fdb-8d83-a385beb0ef9b)
> 

![Screenshot_20230602-102803_GitHub.jpg](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/ecae7aaa-34f5-401b-91fa-1359158245a6)

@k-deepak04 Resolve this issue in your previous issue as well

**Comment by k-deepak04** [comment]
@shreya024 what is failing?
can you provide me more details
i have integrated this in many projects getting this issue first time :(

**Comment by shreya024** [comment]
> @shreya024 what is failing? can you provide me more details i have integrated this in many projects getting this issue first time :(

As you can see it failed in your PR as well.Maybe you need to change EddieHubCommunity name in last PR ,it should be Carbonops right?

**Comment by k-deepak04** [comment]
Nope it is of eddiecommnuity only
you have to do the setting that i mentioned in the comment
