### ISSUE TITLE
Create a Contributing.md

### ISSUE THREAD

**Issue by Pin4sf** [SrijanShovit/carbonops-v2#6]
The repository need a contributing.md markdown file which will help the contributors to understand the contribution process better and will help people who are new to the open source understand the code base and contribution steps better.

**Comment by SrijanShovit** [comment]
Hey @Pin4sf Sorry, actually I was super busy for some 4-5 days.
Thanks for pointing out the thing.
I will add the contributing guidelines.

**Comment by Pin4sf** [comment]
Okay
