### ISSUE TITLE
Feature : Dark Theme

### ISSUE THREAD

**Issue by parasss19** [SrijanShovit/carbonops-v2#62]
## Sample Work (its just a sample you can also provide me the colors you want )

https://github.com/SrijanShovit/carbonops-v2/assets/101205226/915c64d7-941c-44b3-9532-13941c433761

**Comment by parasss19** [comment]
Hi @shreya024 Please review it once

**Comment by shreya024** [comment]
@parasss19 Assigned ! Go for it

**Comment by Abhinavcode13** [comment]
@parasss19 what's your progress?

**Comment by parasss19** [comment]
> @parasss19 what's your progress?

I will make it till Saturday as my exams are ongoing.

**Comment by linga66** [comment]
I want to work on this @shreya024
