### ISSUE TITLE
Bugs in the landing page

### ISSUE THREAD

**Issue by Anubhav6205** [SrijanShovit/carbonops-v2#65]
Please assign me this issue so that I can resolve it under GSSOC-23. This will be my first-ever open-source contribution. Please let me do it.

![image](https://github.com/SrijanShovit/carbonops-v2/assets/82750157/c90bebd4-ef10-4217-ab55-7dbb03268af1)

**Comment by shreya024** [comment]
Closing this as it is the Same issue as #47
