### ISSUE TITLE
The placeholder is missing in  the login page

### ISSUE THREAD

**Issue by HimanshuNarware** [SrijanShovit/carbonops-v2#68]
##Description 
The login form is missing a placeholder, which effecting the readability of the website I want to work on this issue, so please assign me this issue. 
##Screenshot

![134](https://github.com/SrijanShovit/carbonops-v2/assets/83147410/3372cdc6-4022-4719-bf4d-8c09b5cbe64c)

**Comment by SrijanShovit** [comment]
Hello HimanshuNarware, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>
