### ISSUE TITLE
The scrollbar is very simple

### ISSUE THREAD

**Issue by Shreyans2004** [SrijanShovit/carbonops-v2#70]
The website is beautiful but the scrollbar is very simple.
I can add styling to the scrollbar so that it looks more attractive and the website also looks better.
I can change the styling of scrollbar .Can you assign this issue to me?

**Comment by SrijanShovit** [comment]
Hello Shreyans2004, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>
