### ISSUE TITLE
Adding Alert on Login and Signup page

### ISSUE THREAD

**Issue by Hemant2335** [SrijanShovit/carbonops-v2#73]
As of now when you try to login with empty fields  nothing happens which shouldn't be the case so I can

-> Add alerts on both pages when the fields are empty

therefore please assign this task to me

**Comment by SrijanShovit** [comment]
Hello Hemant2335, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
@Hemant2335 Closing this as we will be handling this case via OAuth integration
