### ISSUE TITLE
Radio Buttons in Login

### ISSUE THREAD

**Issue by shreya024** [SrijanShovit/carbonops-v2#74]
## Description:
- In the Login Page,Implement Radio Buttons for choosing Category

**Comment by SrijanShovit** [comment]
Hello shreya024, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by MithileshPandit** [comment]
Hi there! My name is Mithilesh, and I'm excited to help you with your open source contribution. I see that you mentioned implementing radio buttons for choosing categories on the login page. That sounds like a great idea!

As I'm new to open source contribution, could you please provide some more information about the categories you would like to see in the radio buttons? Understanding the specific categories will help me design and implement the feature accurately.

Additionally, if there are any design guidelines or existing patterns in the project that I should follow, please let me know. I want to ensure that my contribution aligns well with the project's standards.

Thank you, and I look forward to your response!

**Comment by shreya024** [comment]
> Hi there! This is Mithilesh. I wanted to inform you that I have started working on implementing the radio buttons for choosing categories on the login page. I understand the requirement and will ensure a seamless user experience. If there are any specific design considerations or guidelines, please let me know. I'll keep you updated on my progress. If you have any further suggestions or feedback, feel free to share.

@MithileshPandit you're supposed to wait till the issue gets assigned to you.And as for the design,implement it such that it matches the current project view.

**Comment by MithileshPandit** [comment]
Got it. Thanks

**Comment by dotarjun** [comment]
Can I be assigned to this issue

**Comment by sagnik-p** [comment]
I want to work on this
Can I be assigned to this issue
