### ISSUE TITLE
[Feature] Footer Section 

### ISSUE THREAD

**Issue by parthpathakpp1** [SrijanShovit/carbonops-v2#77]
I will make a Footer Section for the website . 

Will make Footer Somewhat like this . Will definitely make changes in it .
![gyanagururfooter](https://github.com/SrijanShovit/carbonops-v2/assets/85991449/6bd740ef-8f33-4ea4-badb-dd9acb2bde22)

**Comment by SrijanShovit** [comment]
Hello parthpathakpp1, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by parthpathakpp1** [comment]
Can you assign me this issue under GSSOC'23.

**Comment by shreya024** [comment]
Not required as page already made according to design
