### ISSUE TITLE
[Feature] Backend for Signup Page 

### ISSUE THREAD

**Issue by parthpathakpp1** [SrijanShovit/carbonops-v2#78]
I will create database models and will write backend logic for sign up . So user an Sign up .

**Comment by SrijanShovit** [comment]
Hello parthpathakpp1, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by parthpathakpp1** [comment]
Can you assign me this issue under GSSOC'23.

**Comment by shreya024** [comment]
> Can you assign me this issue under GSSOC'23.

@parthpathakpp1 Can you implement this using OAuth ?

**Comment by shreya024** [comment]
Same as #42
