### ISSUE TITLE
Discuss workflow and beginning with project

### ISSUE THREAD

**Issue by Anjali-Kedia** [SrijanShovit/carbonops-v2#8]
Hey, I went through your project and found it very intriguing. I would love to contribute to it. Can you discuss upon how you want to begin the work on this project?

**Comment by SrijanShovit** [comment]
Sure @Anjali-Kedia 
Sorry I have been busy for past few days.
I will discuss all workflows
Thanks for showing interest

**Comment by shreya024** [comment]
Please refer updated README @Anjali-Kedia
