### ISSUE TITLE
[Feature] Navbar Section 

### ISSUE THREAD

**Issue by parthpathakpp1** [SrijanShovit/carbonops-v2#80]
Navbar needs an improvement . 
- Navigation: The navbar provides a clear and consistent way for users to navigate a website.
- User Experience: It enhances the overall user experience by helping users find information quickly and easily.
- Branding and Identity: The navbar incorporates logos and branding elements to reinforce the website's identity.
- Responsive Design: It adapts to different screen sizes, ensuring a mobile-friendly experience.
- Call to Action: The navbar often includes prominent buttons or links for important actions or engagements.

![carbnopsnavbarissue](https://github.com/SrijanShovit/carbonops-v2/assets/85991449/8658f770-f89b-43be-9347-5182080b6dd7)

**Comment by SrijanShovit** [comment]
Hello parthpathakpp1, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by parthpathakpp1** [comment]
Can you assign me this issue under GSSOC'23.

**Comment by shreya024** [comment]
Closing this as same issue as #25
