### ISSUE TITLE
Add Issue_template

### ISSUE THREAD

**Issue by andoriyaprashant** [SrijanShovit/carbonops-v2#81]
## Description

- I plan to create a Issue template 

## Expected Behavior

Issue template in .github folder with bug_report and feature request 

## Current Behavior

There is no issue template

## GSSOC 2023

**Comment by SrijanShovit** [comment]
Hello andoriyaprashant, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by andoriyaprashant** [comment]
Hello @shreya024 
Please review my Pull request #82 
Thank you

**Comment by shreya024** [comment]
Closing this as it is same as #16
