### ISSUE TITLE
Calculation Functionality

### ISSUE THREAD

**Issue by anuHait** [SrijanShovit/carbonops-v2#83]
Buttons given in the form are not working
I would want to work on creating the backend routes of the project and also on the functionality of the calculation.
Please assign me this issue

**Comment by shreya024** [comment]
@anuHait Implement function to calculate Carbon footprint score according to https://www.wikihow.com/Calculate-Your-Carbon-Footprint

**Comment by anuHait** [comment]
Thankyou for assigning I'll complete the task as soon as possible.
