### ISSUE TITLE
BUG issue template

### ISSUE THREAD

**Issue by Abhinavcode13** [SrijanShovit/carbonops-v2#87]
The template may include specific sections to capture relevant information, such as the environment in which the bug occurred, the version of the software being used, or any specific configurations. This ensures that all the necessary details are captured, which can be crucial for reproducing and fixing the bug.

**Comment by SrijanShovit** [comment]
Hello Abhinavcode13, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by Abhinavcode13** [comment]
please assign this issue to me @shreya024

**Comment by shreya024** [comment]
Closing this as not required
