### ISSUE TITLE
Want to add hover effect on the home page image

### ISSUE THREAD

**Issue by HimanshuNarware** [SrijanShovit/carbonops-v2#89]
##Description
I want to add a hover effect on the home page image it will improve the UI of the website

##screenshot
![167](https://github.com/SrijanShovit/carbonops-v2/assets/83147410/159da9b9-2ce7-40a5-8009-663a1562ac51)

**Comment by SrijanShovit** [comment]
Hello HimanshuNarware, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Closing this as not required
