### ISSUE TITLE
feat: password visibility toggle button in signup

### ISSUE THREAD

**Issue by SINJINI-G** [SrijanShovit/carbonops-v2#91]
Hi @shreya024 !

I will add the password visibility toggle button in signup (both for individuals and organisations). Can you please assign this issue to me for gssoc?

**Comment by SrijanShovit** [comment]
Hello SINJINI-G, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
@SINJINI-G Implement along with #90
