### ISSUE TITLE
feat: theme toggle button

### ISSUE THREAD

**Issue by SINJINI-G** [SrijanShovit/carbonops-v2#92]
Hi @shreya024 !!

I will add the toggle button to change dark theme and light theme. Can you please assign this issue to me under gssoc?

**Comment by SrijanShovit** [comment]
Hello SINJINI-G, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Closing this as same issue as #62
