### ISSUE TITLE
feat: Google Authentication UI

### ISSUE THREAD

**Issue by SINJINI-G** [SrijanShovit/carbonops-v2#93]
Hi @shreya024 !!

In the signup page, there is no option to signup with google. I will make the UI of this. Can you please assign this issue to me under gssoc?

**Comment by SrijanShovit** [comment]
Hello SINJINI-G, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>
