### ISSUE TITLE
Display contributors on readme

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [SrijanShovit/carbonops-v2#98]
If you're interested and this seems a good idea to you, we can display all the project contributors on the readme.

**Comment by SrijanShovit** [comment]
Hello Soumya-Kushwaha, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
@Closing this as Contributors list will be displayed via #44
