### ISSUE TITLE
Bug: login option is not working

### ISSUE THREAD

**Issue by suzy-g38** [SrijanShovit/carbonops-v2#99]
The login page is not working, clicking on the login button nothing is happening

I would like to work on it under gssoc'23

**Comment by SrijanShovit** [comment]
Hello suzy-g38, thanks for opening a issue, your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible.<p></p>

**Comment by shreya024** [comment]
Closing as same as #42. @suzy-g38 if you want to work on #42 comment there to get assigned
